import './globals.css'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import Footer1st from './components/footer1st/page'

const inter = Inter({ subsets: ['latin'] })

const poppins = Poppins({
  subsets: ['latin'],
  weight : ['300', '400', '500', '600', '700'],
  variable : '--font-poppins',
  style: ['normal','italic'],
  display: 'swap',
})

export const metadata = {
  title: 'Warung Kompetensi Pegawai BPS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        <footer>
          <Footer1st/>
        </footer>
      </body>
    </html>
  )
}
